name: FT Deployment Pipeline
on: [push, workflow_dispatch]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint


  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps: 
      - name: code checkout
        uses: actions/checkout@v3
      # - name: configure node js  NOT NEEDED AS RUNNER ALREADY HAS NODE JS
      #   uses: actions/setup-nodejs
        # with:
        #   node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm test


  deploy-job:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps: 
    - name: code checkout
      uses: actions/checkout@v3
    - name: install dependencies
      run: npm ci
    - name: Create Build
      run: npm build
    - name: Deploy
      run: echo "Deploying"
